# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/risc.xdc

# IP: ip/instruction_memory_3/instruction_memory.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==instruction_memory || ORIG_REF_NAME==instruction_memory} -quiet] -quiet
