# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/thean_f8wkkz4/Documents/kgp_risc/kgp_risc.runs/synth_1/risc.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 4
set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/thean_f8wkkz4/Documents/kgp_risc/kgp_risc.cache/wt [current_project]
set_property parent.project_path C:/Users/thean_f8wkkz4/Documents/kgp_risc/kgp_risc.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/thean_f8wkkz4/Documents/kgp_risc/kgp_risc.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files C:/Users/thean_f8wkkz4/Documents/kgp_risc/kgp_risc.srcs/sources_1/ip/instruction_memory_2/sampleim.coe
add_files C:/Users/thean_f8wkkz4/sampledm.coe
add_files C:/Users/thean_f8wkkz4/sumofnum.coe
add_files C:/Users/thean_f8wkkz4/Documents/kgp_risc/kgp_risc.srcs/sources_1/ip/factorial.coe
add_files C:/Users/thean_f8wkkz4/Documents/kgp_risc/kgp_risc.srcs/sources_1/ip/gcd.coe
add_files C:/Users/thean_f8wkkz4/Documents/kgp_risc/kgp_risc.srcs/sources_1/ip/insertion_sort_data.coe
add_files C:/Users/thean_f8wkkz4/Documents/kgp_risc/kgp_risc.srcs/sources_1/ip/insertion_sort.coe
add_files C:/Users/thean_f8wkkz4/Documents/kgp_risc/kgp_risc.srcs/sources_1/ip/factorial_data.coe
add_files C:/Users/thean_f8wkkz4/Documents/kgp_risc/kgp_risc.srcs/sources_1/ip/booth_mul.coe
add_files C:/Users/thean_f8wkkz4/Documents/kgp_risc/kgp_risc.srcs/sources_1/ip/booth_mul_data.coe
add_files c:/Users/thean_f8wkkz4/Documents/kgp_risc/kgp_risc.srcs/sources_1/ip/div.coe
add_files c:/Users/thean_f8wkkz4/Documents/kgp_risc/kgp_risc.srcs/sources_1/ip/div_data.coe
add_files c:/Users/thean_f8wkkz4/Documents/kgp_risc/kgp_risc.srcs/sources_1/ip/test.coe
add_files c:/Users/thean_f8wkkz4/Documents/kgp_risc/kgp_risc.srcs/sources_1/ip/test_data.coe
read_mem C:/Users/thean_f8wkkz4/Downloads/Lab_Day_15/instructions.mem
read_verilog -library xil_defaultlib {
  C:/Users/thean_f8wkkz4/Downloads/Lab_Day_15/program_counter.v
  C:/Users/thean_f8wkkz4/Downloads/Lab_Day_15/RISC.v
  C:/Users/thean_f8wkkz4/Downloads/Lab_Day_15/instruction_decoding.v
  C:/Users/thean_f8wkkz4/Downloads/Lab_Day_15/mem.v
  C:/Users/thean_f8wkkz4/Downloads/Lab_Day_15/branching_mechanism.v
  C:/Users/thean_f8wkkz4/Downloads/Lab_Day_15/alu_integration.v
  C:/Users/thean_f8wkkz4/Downloads/Lab_Day_15/mux_s.v
  C:/Users/thean_f8wkkz4/Downloads/Lab_Day_15/register_bank.v
  C:/Users/thean_f8wkkz4/Downloads/Lab_Day_15/main_control.v
  C:/Users/thean_f8wkkz4/Downloads/Lab_Day_15/instruction_mem.v
  C:/Users/thean_f8wkkz4/Downloads/12thoct/not_32_bit.v
  C:/Users/thean_f8wkkz4/Downloads/12thoct/adder_32_bit.v
  C:/Users/thean_f8wkkz4/Downloads/12thoct/or_32_bit.v
  C:/Users/thean_f8wkkz4/Downloads/12thoct/or_alu.v
  C:/Users/thean_f8wkkz4/Downloads/12thoct/sll_32_bit.v
  C:/Users/thean_f8wkkz4/Downloads/12thoct/subtractor_32_bit.v
  C:/Users/thean_f8wkkz4/Downloads/12thoct/sgt_32_bit.v
  C:/Users/thean_f8wkkz4/Downloads/12thoct/2_bit_adder.v
  C:/Users/thean_f8wkkz4/Downloads/12thoct/not_alu.v
  C:/Users/thean_f8wkkz4/Downloads/12thoct/sra_32_bit.v
  C:/Users/thean_f8wkkz4/Downloads/12thoct/lui_32_bit.v
  C:/Users/thean_f8wkkz4/Downloads/12thoct/xor_32_bit.v
  C:/Users/thean_f8wkkz4/Downloads/12thoct/and_32_bit.v
  C:/Users/thean_f8wkkz4/Downloads/12thoct/hamm_alu.v
  C:/Users/thean_f8wkkz4/Downloads/12thoct/slt_32_bit.v
  C:/Users/thean_f8wkkz4/Downloads/12thoct/ham_32_bit.v
  C:/Users/thean_f8wkkz4/Downloads/12thoct/srl_32_bit.v
  C:/Users/thean_f8wkkz4/Downloads/12thoct/nor_32_bit.v
  C:/Users/thean_f8wkkz4/Downloads/12thoct/full_adder_structural.v
  C:/Users/thean_f8wkkz4/Downloads/12thoct/xor_alu.v
  C:/Users/thean_f8wkkz4/Downloads/12thoct/3_bit_adder.v
  C:/Users/thean_f8wkkz4/Downloads/12thoct/and_alu.v
  C:/Users/thean_f8wkkz4/Documents/kgp_risc/kgp_risc.srcs/sources_1/new/alu_control_decoder.v
  C:/Users/thean_f8wkkz4/Documents/kgp_risc/kgp_risc.srcs/sources_1/new/cmov.v
  C:/Users/thean_f8wkkz4/Documents/kgp_risc/kgp_risc.srcs/sources_1/new/clkdiv.v
}
read_ip -quiet C:/Users/thean_f8wkkz4/Documents/kgp_risc/kgp_risc.srcs/sources_1/ip/instruction_memory_3/instruction_memory.xci
set_property used_in_implementation false [get_files -all c:/Users/thean_f8wkkz4/Documents/kgp_risc/kgp_risc.gen/sources_1/ip/instruction_memory_3/instruction_memory_ooc.xdc]

read_ip -quiet C:/Users/thean_f8wkkz4/Documents/kgp_risc/kgp_risc.srcs/sources_1/ip/data_memory_2/data_memory.xci
set_property used_in_implementation false [get_files -all c:/Users/thean_f8wkkz4/Documents/kgp_risc/kgp_risc.gen/sources_1/ip/data_memory_2/data_memory_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/thean_f8wkkz4/Documents/kgp_risc/kgp_risc.srcs/constrs_1/new/risc.xdc
set_property used_in_implementation false [get_files C:/Users/thean_f8wkkz4/Documents/kgp_risc/kgp_risc.srcs/constrs_1/new/risc.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental C:/Users/thean_f8wkkz4/Documents/kgp_risc/kgp_risc.srcs/utils_1/imports/synth_1/risc.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top risc -part xc7a100tcsg324-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef risc.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file risc_utilization_synth.rpt -pb risc_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
